org.gradle.jvmargs=-Xmx6G -XX:MaxMetaspaceSize=3G -XX:ReservedCodeCacheSize=512m -Dkotlin.daemon.jvm.options\="-Xmx3G" -XX:+HeapDumpOnOutOfMemoryError

android.useAndroidX=true
android.enableJetifier=true

org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.workers.max=2

kotlin.incremental=false